version: "2"
services:

  tor:
    image: chpio/tor:latest
    volumes:
      - "./data-tor:/data/tor"
    network_mode: "service:electrum-server"

  bitcoind:
    image: chpio/bitcoind-tor:latest
    volumes:
      - "./data-bitcoind:/data/bitcoind"
    network_mode: "service:electrum-server"
    command:
      - "-txindex=1"
      - "-rest"

  electrum-server:
    image: chpio/electrum-server:latest
    volumes:
      - "./data-electrumx-server:/data/electrumx-server"
    ports:
      - "50001:50001"
